### ISSUE TITLE
Re-export dependencies

### ISSUE THREAD

**Issue by nearmax** [near/near-sdk-rs#142]
Currently contract developers have to export the following libraries along with `near-sdk` themselves:

```toml
[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.45"
borsh = "0.6.0"
wee_alloc = { version = "0.4.5", default-features = false, features = [] }
```

The problem with that is that it makes DevX slightly worse and can create version mismatch, e.g. `near_sdk::collections` can use different version of `borsh` which will produce an obscure compilation error. We should export them into `near_sdk` and then contracts can access them from `near_sdk::exports::`. This is a common practice in Rust crates, e.g. see syn.
