### ISSUE TITLE
chained promises with nesting are executed out of order

### ISSUE THREAD

**Issue by oysterpack** [near/near-sdk-rs#263]
## Example
```rust
let promise_1 = ...
let promise_2 = ...
let promise_3 = ...

// [promise_1 -> promise_2 -> promise_3] - expected execution order
// [promise_2 -> promise_1 -> promise_3] - actual execution order
promise_1.then(promise_2.then(promise_3))

// execution should be the same as:
promise_1.then(promise_2).then(promise_3);
```

I am using:
```toml
[dependencies]
near-sdk = { git = "https://github.com/near/near-sdk-rs",  tag = "2.3.0" }
```
