### ISSUE TITLE
Using sdk should not entail compiling rocksdb

### ISSUE THREAD

**Issue by matklad** [near/near-sdk-rs#561]
See [https://old.reddit.com/r/rust/comments/pheews/rustanalyzer_slow_and_makes_huge_folders/](https://old.reddit.com/r/rust/comments/pheews/rustanalyzer_slow_and_makes_huge_folders/) – someone is having trouble writing a near contract, because SDK is too big.

I quickly looked at what their project produces, and one things that jumps at me is rocksdb:

```
 λ dust -n 10 -w 40
 955M ┌── deps
 150M │ ┌── db
 308M │ ┌─┴ rocksdb
 320M │ ├── librocksdb.a
 645M │ ┌─┴ out
 646M │ ┌─┴ librocksdb-sys-d36a00c91..
 1.0G ├─┴ build
 1.9G ┌─┴ debug
 1.9G ┌─┴ target
 1.9G ┌─┴ .
 ```

650M is nothing to sneeze at, **and** compiling rocksdb takes a lot of time. Here's the Cargo.toml that produces this output:

```toml
 <span class="error">[package]</span>
 name = "neart"
 version = "0.1.0"
 authors = []
 edition = "2018"

<span class="error">[lib]</span>
 crate-type = <span class="error">["cdylib", "rlib"]</span>

<span class="error">[dependencies]</span>
 near-sdk = "3.1.0"
 near-contract-standards = "3.1.0"
 uint = 

 { version = "0.9.0", default-features = false } 

<span class="error">[dev-dependencies]</span>
 near-sdk-sim = "3.2.0"

<span class="error">[profile.release]</span>
 codegen-units=1
 opt-level = "z"
 lto = true
 debug = false
 panic = "abort"
 overflow-checks = true
 ```

I don't think anything here **fundamentally** requires rocks. I think it is used by simulator for some caches, but, given the size of dependency, it's better to write some code to use the file system directly – we don't care about durability in sim, but we do care about people running `cargo check` not not being surprised by the amount of dependencies.
