### ISSUE TITLE
Using type 'Self' in metadata! macro fails to compile

### ISSUE THREAD

**Issue by tzann** [near/near-sdk-rs#690]
When using 'Self' as a type inside the `metadata!` macro, the compiler gives this error:
 ```
 error<span class="error">[E0433]</span>: failed to resolve: use of undeclared type `Self`
 --> src/lib.rs:14:21

<div class="table-wrap"> 
</div>

14 | pub fn new() -> Self {

<div class="table-wrap">
  | ^^^^ use of undeclared type `Self` ``` | 
</div>

For example, this contract fails to compile with `RUSTFLAGS='-C link-arg=-s' cargo build --target wasm32-unknown-unknown --release`, yielding the error mentioned above. Removing the `metadata!` macro makes it compile successfully.
 ```rust
 use near_sdk::borsh::

 {self, BorshDeserialize, BorshSerialize} 

;
 use near_sdk::

 {metadata, near_bindgen, PanicOnDefault} 

;

metadata! {

#<span class="error">[near_bindgen]</span>
 #<span class="error">[derive(BorshDeserialize, BorshSerialize, PanicOnDefault)]</span>
 pub struct StatusMessage {
 }

#<span class="error">[near_bindgen]</span>
 impl StatusMessage {
 #<span class="error">[init]</span>
 pub fn new() -> Self {
 Self {
 }
 }
 }

}
 ```
 Cargo.toml:
 ```toml
 <span class="error">[package]</span>
 name = "test"
 version = "0.1.0"
 edition = "2018"

<span class="error">[lib]</span>
 crate-type = <span class="error">["cdylib"]</span>

<span class="error">[dependencies]</span>
 near-sdk = "3.1.0"
 near-sdk-macros = "3.1.0"

<span class="error">[profile.release]</span>
 codegen-units = 1

1.  Tell `rustc` to optimize for small code size.
     opt-level = "z"
     lto = true
     debug = false
     panic = "abort"
     overflow-checks = true
     ```
